### ISSUE TITLE
snap-aligner running single-threaded instead of multi-threaded

### ISSUE THREAD

**Issue by Pinnipeds** [blahah/transrate#174]
I'm trying to run Transrate with read mapping option. I ran transrate-1.0.1-linux-x86_64/transrate --assembly /mnt/transrate/Trinity.blubber.fixed.fa \
--left /100G/assembly/left.fq \
--right /100G/assembly/right.fq \
--threads 8

However, the snap-aligner has been running single-threaded for over 2 days. Is this normal?

**Comment by Blahah** [comment]
This is not normal! Possibly a bug in SNAP - there have been a few more bugfix releases since the last transrate release.

Some SNAP bugs are non-deterministic, so if you kill the process, delete any `.bam` files that have been created, and then re-run the transrate command, it may work fine. If not...

We'll push out a new transrate release very soon (tomorrow I hope) that will include the newest SNAP, and this might solve your problem. If not...

Let me know and we'll see what we need to do to debug.

**Comment by blahah** [comment]
Our latest release is [v1.0.3](https://github.com/blahah/transrate/releases/tag/v1.0.3) - it includes a new version of SNAP and Salmon. Hopefully it fixes this, but if you still see it please re-open the issue.
