### ISSUE TITLE
Discrepancy in ORF count between contigs.csv and assemblies.csv

### ISSUE THREAD

**Issue by zagorGit** [Blahah/transrate#239]
We noticed discrepancy between n_with_orf from assemblies.csv file and number of sequences from 
contigs.csv file where values in orf_length exist, or are > 50nt or even > 50aa.
How is n_with_orf actually calculated?

**Comment by blahah** [comment]
Hey, yeah we set an arbitrary limit of 50aa in order to avoid spurious false tiny ORFs causing issues, I think.

However, in hindsight that was a spurious heuristic to apply. We could change it to a CLI option, and you can change the code here to adjust it for your own use case: https://github.com/blahah/transrate/blob/91fb81a89f9fd73d28de2ad34074ec193c99b41b/lib/transrate/assembly.rb#L162-L164

**Comment by zagorGit** [comment]
great, thnx!

I suggest to rename _'n_with_orf'_ then to _n_with_orf > 149 nt_ key name, or similar, not to confuse users and reviewers
